language: node_js
node_js:
- '11'

cache: npm

addons:
  hosts:
    - vultr

before_install:
- chmod 600 ~/.ssh/config
- echo "Host vultr" >> ~/.ssh/config
- echo "  HostName $HostName" >> ~/.ssh/config
- echo "  User git" >> ~/.ssh/config
- echo "  Port $Port" >> ~/.ssh/config
- echo "  StrictHostKeyChecking yes" >> ~/.ssh/config
- echo "  IdentityFile ~/.ssh/blog_server_rsa" >> ~/.ssh/config
- cat ~/.ssh/config
- cat /etc/hosts
- openssl aes-256-cbc -K $encrypted_2c1446b86c6a_key -iv $encrypted_2c1446b86c6a_iv -in blog_server_rsa.enc -out ~/.ssh/blog_server_rsa -d
- chmod 600 ~/.ssh/blog_server_rsa
- export TZ='Asia/Beijing'
- npm install -g hexo-cli
install:
- npm install
branches:
  only:
  - source
script:
- hexo clean
- hexo generate
after_success:
- git config --local user.name "roastduckcd"
- git config --local user.email "sjy457346652@aliyun.com"
- sed -i'' "s~git@github.com:~https://${GITHUB_TOKEN}@github.com/~" _config.yml
- sed -i'' "s~git@git.dev.tencent.com:~https://${CODING_TOKEN}@git.dev.tencent.com/~"
  _config.yml
- hexo deploy
